### PR TITLE
buildStatus HTTP handling

### PR DESCRIPTION
**Pull request by cachedout**
## What does this PR do?
Fixes an issue where this module doesn't correctly follow HTTP 301s. Instead of more sophisticated handling of HTTP, it's easier just to point at the hosts as they are currently configured. :) 

## Why is it important?
Corrects a potential failure in downstream users of this module, as as the release job for the APM Java Agent team.

## Related issues
None. Discovered while debugging other issues.

### CODE REVIEW

**Review by v1v — APPROVED** [review]
👍

**Review by mdelapenya — APPROVED** [review]

**Comment by cachedout** [comment]
jenkins, run the tests

**Comment by cachedout** [comment]
jenkins, run the tests

**Comment by cachedout** [comment]
Closed in favor of https://github.com/elastic/apm-pipeline-library/pull/852

**Pull request closed without merging**
