### PR TITLE
Move from observablt-robots-on-call to observablt-robots

### PR DESCRIPTION
**Pull request by amannocci**
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>

## What does this PR do?

Use `elastic/observablt-robots` group instead of `elastic/observablt-robots-on-call`.

## Why is it important?

There is no rotation anymore for on-call.

### CODE REVIEW

**Review by v1v — COMMENTED** [review]
I'd say to use the new team `elastic/observablt-ci` instead, since `elastic/observablt-robots` is the generic one.

**Comment by amannocci** [comment]
> I'd say to use the new team `elastic/observablt-ci` instead, since `elastic/observablt-robots` is the generic one.

Do we maintain all those scripts?

**Comment by v1v** [comment]
> Do we maintain all those scripts?

I don't understand your question, do you mean if we are the ones maintaining this repository?

**Comment by amannocci** [comment]
Yes, you are right. Do we maintain all of them? If that's the case, then we can use the more specific one.

**Comment by v1v** [comment]
> Yes, you are right. Do we maintain all of them? If that's the case, then we can use the more specific one.

I'd say yes, there are just a few files related to the OTEL integration for `pytest` that @kuisathaverat maintains and might eventually move to somewhere else. Since this project is quite specific for the CI, I'd say to use the specific team

**Review by v1v — APPROVED** [review]

**Pull request merged**
