### PR TITLE
bugfix for issue #1840

### LINKED ISSUE #1840: pytest_otel: pytest.fail is not captured as an error
Extremely reduced test:

```
import pytest
def test_me():
  pytest.fail(reason='cucu')
```

This won't be shown as an error (_the red exclamation mark_ in the failed **child** span) because `pytest_runtest_call` hook won't see `hasattr(sys, "last_value")` etc... in the **call phase**.
So the problem is that you will find a general error in the overall parent trace span  (_a red exclamation mark_ only in the **parent** span) but not a corresponding error in the child test case where the `pytest.fail` is.
Screenshot below showing the issue in the current version of pytest_otel.

immagine

or you can print the textual output with the debug flag `pytest test_pyfail.py --otel-debug True`:
Using on memory OpenTelemetry exporter, notice the wrong `"tests.status": "passed"` of the `"Running test_me"` span
```json
Number of spans: 2
[
{
    "name": "Running test_me",
    "context": {
        "trace_id": "0x3b0906ff845c25fe5a0813ddb257d362",
        "span_id": "0x3ef82e9a1a17c802",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xeca1b844f01c1bb5",
    "start_time": "2022-08-18T06:08:48.954851Z",
    "end_time": "2022-08-18T06:08:49.954961Z",
    "status": {
        "status_code": "OK"
    },
    "attributes": {
        "tests.name": "test_me",
        "tests.status": "passed"
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.11.0",
        "service.name": "Pytest_Otel_reporter"
    }
},{
    "name": "Test Suite",
    "context": {
        "trace_id": "0x3b0906ff845c25fe5a0813ddb257d362",
        "span_id": "0xeca1b844f01c1bb5",
        "trace_state": "[]"
    },
    "kind": "SpanKind.SERVER",
    "parent_id": null,
    "start_time": "2022-08-18T06:08:48.861039Z",
    "end_time": "2022-08-18T06:08:49.965561Z",
    "status": {
        "status_code": "ERROR"
    },
    "attributes": {
        "tests.status": "failed"
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.11.0",
        "service.name": "Pytest_Otel_reporter"
    }
}
]
```

My proposed solution is to move - or even better to copy - the above hook into` pytest_runtest_makereport` with further benefit of showing the timing of setup vs call vs teardown (notice that only the latter, namely the **teardown phase**,  captures `pytest.fail` exception)

Here below a screenshot (if also the original `pytest_runtest_call` hook is kept there will be 3 new reporting spans aside from the running span, which could be better kept in order to see the test running time elapsed) and the code with my proposed change.

immagine

```
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
#def pytest_runtest_call(item):
    global outcome, session_name, spans, curr_span
    print("pytest_runtest_makereport ", call.when)
    # if call.when != "call":
    #     yield
    # else:
    with tracer.start_as_current_span(
        "Report {} {}".format(call.when, item.name),
        context=trace.set_span_in_context(spans[session_name]),
        record_exception=True,
        set_status_on_exception=True,
    ) as span:
        #total_counter.add(1)
        LOGGER.debug("Test {} starts - {}".format(item.name, span.get_span_context()))
        span.set_attribute("tests.name", item.name)
        yield
        LOGGER.debug("Test {} ends - {}".format(item.name, span.get_span_context()))

        if hasattr(sys, "last_value") and hasattr(sys, "last_traceback") and hasattr(sys, "last_type"):
            longrepr = ""
            last_value = getattr(sys, 'last_value')
            last_traceback = getattr(sys, 'last_traceback')
            last_type = getattr(sys, 'last_type')

            if not isinstance(last_value, _pytest._code.ExceptionInfo):
                outcome = "failed"
                longrepr = last_value
            elif isinstance(last_value, _pytest._code.skip.Exception):
                outcome = "skipped"
                r = last_value._getreprcrash()
                longrepr = (str(r.path), r.lineno, r.message)
            else:
                outcome = "failed"
                style = item.config.getoption("tbstyle", "auto")
                longrepr = item._repr_failure_py(last_value, style=style)

            stack_trace = repr(traceback.format_exception(last_type, last_value, last_traceback))
            span.set_attribute("tests.error", "{}".format(stack_trace))
            if hasattr(last_value, "args") and len(getattr(last_value, 'args', [])) > 0:
                span.set_attribute("tests.message", "{}"
                                   .format(last_value.args[0]))

            if longrepr:
                span.set_attribute("tests.message", "{}".format(longrepr))
            elif last_value:
                span.set_attribute("tests.message", "{}".format(last_value))
            elif last_type:
                span.set_attribute("tests.message", "{}".format(last_type))

            skipping = getattr(_pytest, 'skipping', None)
            if skipping:
                key = getattr(skipping, 'xfailed_key', None)
                xfailed = item._store.get(key, None)
                reason = getattr(xfailed, 'reason', None)
                if reason :
                    span.set_attribute("tests.message", "{}".format(reason))

        #update_metrics(outcome)
        status = convertOutcome(outcome)
        span.set_status(status)
        span.set_attribute("tests.status", "{}".format(outcome))

```
In conclusion the existing running span is important to track the test duration (as a proof, add a `time.sleep(1)` and you'll see that in the running span) but the new teardown reporting span is important to intercept a possible `pytest.fail` for any single test case.
Finally it's worth sending `pytest.fail` reason\message to the trace:

```diff
diff --git a/pytest_otel_issues_1840/__init__.py b/pytest_otel_issues_1840/__init__.py
index 5bf81a0..69150ea 100644
--- a/pytest_otel_issues_1840/__init__.py
+++ b/pytest_otel_issues_1840/__init__.py
@@ -360,7 +360,10 @@ def pytest_runtest_makereport(item, call):
         #total_counter.add(1)
         LOGGER.debug("Test {} starts - {}".format(item.name, span.get_span_context()))
         span.set_attribute("tests.name", item.name)
-        yield
+        yield_outcome = yield
+        report = yield_outcome.get_result()
+        if report.longrepr:
+            span.set_attribute("tests.message", "{}".format(report.longrepr))
         LOGGER.debug("Test {} ends - {}".format(item.name, span.get_span_context()))

         if hasattr(sys, "last_value") and hasattr(sys, "last_traceback") and hasattr(sys, "last_type"):
```
to get it traced into the other new "Report call" span
immagine

Eventually I wonder whether those 3+1 spans should have a common grouping parent span, summarizing the total duration and the correct outcome and message of the test case. I'm not sure how to code it.

Of course I'd appreciate a feedback about any aspect of this issue. Thanks.

### PR DESCRIPTION
**Pull request by giuliohome**
bugfix for issue #1840 - see my comment https://github.com/elastic/apm-pipeline-library/issues/1840#issuecomment-1218565123

## What does this PR do?

This is fixing the issue https://github.com/elastic/apm-pipeline-library/issues/1840

## Why is it important?

Here is the test output.
Notice that now the child span "Running test_me" is correctly set to `"status_code": "ERROR"` and reports `"tests.status": "failed"` and `"tests.message": "cucu"` from `pytest.fail`'s reason.

```batch
pytest test_pyfail.py --otel-debug True
================================================= test session starts =================================================
platform win32 -- Python 3.9.0, pytest-7.1.2, pluggy-0.13.1
rootdir: C:\giulio\test
plugins: hypothesis-6.48.3, html-3.1.1, metadata-2.0.1, otel-1.1.1
collected 1 item

test_pyfail.py F                                                                                                 [100%]
Using on memory OpenTelemetry exporter
Number of spans: 2
```
```json
[
{
    "name": "Running test_me",
    "context": {
        "trace_id": "0x8074bc7a2fe644a72927e5f3e1a11994",
        "span_id": "0x7187ed36c50ce4f8",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xf2ec6d3e90f92af0",
    "start_time": "2022-08-18T06:45:17.814574Z",
    "end_time": "2022-08-18T06:45:18.814853Z",
    "status": {
        "status_code": "ERROR"
    },
    "attributes": {
        "tests.name": "test_me",
        "tests.message": "cucu",
        "tests.status": "failed"
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.11.0",
        "service.name": "Pytest_Otel_reporter"
    }
},{
    "name": "Test Suite",
    "context": {
        "trace_id": "0x8074bc7a2fe644a72927e5f3e1a11994",
        "span_id": "0xf2ec6d3e90f92af0",
        "trace_state": "[]"
    },
    "kind": "SpanKind.SERVER",
    "parent_id": null,
    "start_time": "2022-08-18T06:45:17.718877Z",
    "end_time": "2022-08-18T06:45:18.827129Z",
    "status": {
        "status_code": "ERROR"
    },
    "attributes": {
        "tests.status": "failed"
    },
    "events": [],
    "links": [],
    "resource": {
        "telemetry.sdk.language": "python",
        "telemetry.sdk.name": "opentelemetry",
        "telemetry.sdk.version": "1.11.0",
        "service.name": "Pytest_Otel_reporter"
    }
}
]
```

## Related issues
No other issues afaik, just
Closes #1840

### CODE REVIEW

**Comment by kuisathaverat** [comment]
thanks for your contribution.

**Comment by kuisathaverat** [comment]
@giuliohome to be able to merge the fix we will need you to sign the CLA at https://www.elastic.co/contributor-agreement

**Comment by giuliohome** [comment]
> @giuliohome to be able to merge the fix we will need you to sign the CLA at https://www.elastic.co/contributor-agreement

I've tried many times, I'm going to do it again now...
But... Just in case, can I send the pdf  to someone in order to close this task on my side?
Thank you

**Comment by kuisathaverat** [comment]
@giuliohome it is signed now. Thank you so much for your time to improve the pytest plugin. I will bump the OpenTelemetry version and release a new version soon

**Review by kuisathaverat — APPROVED** [review]

**Review by v1v — APPROVED** [review]

**Pull request merged**
