### PR TITLE
feat: filebeat pipeline step

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

* Adds Filebeat to the packer cache
* Adds the `filebeat` pipeline step to run Filebeat easily.

## Why is it important?

This new `filebeat` pipeline step allows grabbing the Docker container logs with a couple of steps.

```
pipeline {
  agent { label "ubuntu" }
  stages {
    stage('My Docker tests') {
      steps {
        filebeat(workdir: "${env.WORKSPACE}")
        sh('docker run busybox  ls')
      }
      post {
        cleanup{
          script {
            filebeat.stop(workdir: "${env.WORKSPACE}")
          }
        }
      }
    }
  }
}
```

```
pipeline {
  agent { label "ubuntu" }
  stages {
    stage('My Docker tests') {
      steps {
        filebeat(workdir: "${env.WORKSPACE}"){
        sh('docker run busybox  ls')

        }
      }
    }
  }
}
```

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by mdelapenya — APPROVED** [review]
This is super cool! 👏

**Review by v1v — APPROVED** [review]
NIT: Do you think using it as closure could be an easy approach?  For instance:

```
filebeat(....) {
   sh('docker run busybox  ls')
   sh('docker run busybox  exit 1')
}  
```

💯

**Comment by kuisathaverat** [comment]
> NIT: Do you think using it as closure could be an easy approach? For instance:
> 
> ```
> filebeat(....) {
>    sh('docker run busybox  ls')
>    sh('docker run busybox  exit 1')
> }  
> ```
> 
> 💯

we can have it also for free

**Pull request merged**
