### PR TITLE
pre-commit install always

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

install pre-commit regardless of the exiting installation in the CI workers

## Why is it important?

Cannot trust the CI workers since the pre-commit can be corrupted

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
This seems fine but it's also really strange. Is the shell really failing detect to the installation of pre-commit?

**Comment by v1v** [comment]
> This seems fine but it's also really strange. Is the shell really failing detect to the installation of pre-commit?

The error is not related to this library but somehow the installed `pre-commit` in the CI workers, that failed with:

```
[2022-11-07T15:07:32.674Z] + pre-commit install --install-hooks
[2022-11-07T15:07:33.076Z] pre-commit installed at .git/hooks/pre-commit
[2022-11-07T15:07:33.076Z] [INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[2022-11-07T15:07:33.678Z] [INFO] Initializing environment for https://github.com/elastic/apm-pipeline-library.git.
[2022-11-07T15:07:34.882Z] [INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[2022-11-07T15:07:34.882Z] [INFO] Once installed this environment will be reused.
[2022-11-07T15:07:34.882Z] [INFO] This may take a few minutes...
[2022-11-07T15:07:38.291Z] An unexpected error has occurred: CalledProcessError: command: ('/var/lib/jenkins/workspace/Beats_beats_main/.cache/pre-commit/repov1GWRT/py_env-python2.7/bin/python', u'/var/lib/jenkins/workspace/Beats_beats_main/.cache/pre-commit/repov1GWRT/py_env-python2.7/bin/pip', 'install', '.')
[2022-11-07T15:07:38.291Z] return code: 1
[2022-11-07T15:07:38.291Z] expected return code: 0
[2022-11-07T15:07:38.291Z] stdout:
[2022-11-07T15:07:38.291Z]     Processing /var/lib/jenkins/workspace/Beats_beats_main/.cache/pre-commit/repov1GWRT
[2022-11-07T15:07:38.291Z]     
[2022-11-07T15:07:38.292Z] stderr:
[2022-11-07T15:07:38.292Z]     DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
[2022-11-07T15:07:38.292Z]     ERROR: Package 'pre-commit-hooks' requires a different Python: 2.7.17 not in '>=3.6.1'
```

https://github.com/elastic/beats/issues/33596

**Comment by cachedout** [comment]
Ah. So the idea is that somehow `pre-commit` was already present on these systems but it was broken?

**Comment by v1v** [comment]
> Ah. So the idea is that somehow pre-commit was already present on these systems but it was broken?

That's correct

**Pull request merged**
