### PR TITLE
standardise the issueCommentTrigger with obltGitHubComments

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Create a step with the default GitHub comments that are supported to trigger a build in the CI.

It adds `^` in the `Jenkins run the tests` comment and `^/test`.

## Why is it important?

To normalise the GitHub comments, then we can avoid hardcoded comments and have one place to rule out the same default behaviour in all the obs11 projects.

## Related issues

https://github.com/elastic/apm-pipeline-library/pull/1278

## Tests

These test sections reflects how this new step could be used in the pipelines were changed.

Comment https://github.com/elastic/apm-pipeline-library/pull/1281#issuecomment-921046689

Triggered

image

While https://github.com/elastic/apm-pipeline-library/pull/1281#issuecomment-921095119 didn't trigger any build, since it did not start with `Jenkins ....`

### CODE REVIEW

**Comment by kuisathaverat** [comment]
Could we put that string in a step and use it in all the pipelines?


```
 triggers {
    issueCommentTrigger(commonFlags()+'|^/new-cmd$')
}
```

**Comment by v1v** [comment]
This should not get triggered: Jenkins run the tests please

**Review by kuisathaverat — APPROVED** [review]

**Comment by v1v** [comment]
@mdelapenya and @adam-stokes , I need your review here. is `obsGitHubComments` a good step name?

**Comment by mdelapenya** [comment]
> @mdelapenya and @adam-stokes , I need your review here. is `obsGitHubComments` a good step name?

It's OK to me. I'd like to know if the `obs` prefix is going to be a standard for this kind of common steps. If that's not the case, let's look for a prefix that adds more context about the namespace, something like `oblt` or `o11y`...

**Review by mdelapenya — APPROVED** [review]

**Comment by v1v** [comment]
> It's OK to me. I'd like to know if the obs prefix is going to be a standard for this kind of common steps. If that's not the case, let's look for a prefix that adds more context about the namespace, something like oblt or o11y...

@kuisathaverat @mdelapenya and @adam-stokes  can I ask you to vote for any of the below proposals within this comment?

😄 -> `obsGitHubComments`
👍 -> `obltGitHubComments`
❤️ -> `o11yGitHubComments`

**Comment by adam-stokes** [comment]
+1 on the oblt prefix as that seems to be the standard naming scheme across projects

**Pull request merged**
